name: Dev Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build site (dev)
        run: npm run build:dev

      - name: Wrap dist in dev folder
        run: |
          mkdir -p temp
          mv dist temp/dev

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./temp   # temp contains dev/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4